### GET coffee machines
GET http://{{host}}:{{port}}/machines
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
client.test("Response content-type is json", function() {
  var type = response.contentType.mimeType;
  client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
});
%}

### POST create order
POST http://{{host}}:{{port}}/orders
Accept: application/json
Content-Type: application/json
Authorization: Bearer user1

{
  "coffee": "Cappuccino",
  "machine": "Folk"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
client.test("Response content-type is json", function() {
  var type = response.contentType.mimeType;
  client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
});
%}

### GET status
GET http://{{host}}:{{port}}/orders/949e9bb6-3a36-4c4e-8a36-4a4765d8a5c8
Accept: application/json
Authorization: Bearer user1

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
client.test("Response content-type is json", function() {
  var type = response.contentType.mimeType;
  client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
});
%}

### GET with unknown ID should return 404
GET http://{{host}}:{{port}}/orders/00000-xxxx-zzzz-123123123123
Accept: application/json
Authorization: Bearer user1

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 404, "Response status is not 404");
});
%}

### GET without Authorization header should return 401
GET http://{{host}}:{{port}}/orders/00000-xxxx-zzzz-123123123123
Accept: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 401, "Response status is not 401");
});
%}