### GET health
GET http://{{host}}:{{port}}/health

### GET metrics
GET http://{{host}}:{{port}}/metrics
Accept: application/json

### GET openapi file
GET http://{{host}}:{{port}}/openapi
Accept: application/json